### ISSUE TITLE
Can't read code in your learning environment

### ISSUE THREAD

**Issue by jmcrey** [Samko1928/intro-data-capstone-biodiversity#1]
Unfortunately, I do not have the ability to read the code that is in your learning environment. In order for  your code to be reviewed, it has to be uploaded to GitHub. So, if you would like to have it reviewed, please upload the completed code to GitHub and and comment on this issue with a reference to my name (@jmcrey) stating that the code has been uploaded.

**Comment by Samko1928** [comment]
@jmcrey 
the code has been uploaded

**Comment by Samko1928** [comment]
@jmcrey
the code has been uploaded
